-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Lautaro.

module Lautaro.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Lautaro.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Lautaro.Abs.Ident where
  prt _ (Lautaro.Abs.Ident i) = doc $ showString i
instance Print (Lautaro.Abs.Programme' a) where
  prt i = \case
    Lautaro.Abs.Main _ topdefs stmts -> prPrec i 0 (concatD [prt 0 topdefs, doc (showString "main"), prt 0 stmts, doc (showString "endmain")])

instance Print (Lautaro.Abs.TopDef' a) where
  prt i = \case
    Lautaro.Abs.FnDef _ id_ args type_ stmts -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 type_, doc (showString "in"), prt 0 stmts, doc (showString "endfunction")])
    Lautaro.Abs.FnDefVoid _ id_ args stmts -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "void"), doc (showString "in"), prt 0 stmts, doc (showString "endfunction")])

instance Print [Lautaro.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Lautaro.Abs.Arg' a) where
  prt i = \case
    Lautaro.Abs.ArgVal _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    Lautaro.Abs.ArgRef _ type_ id_ -> prPrec i 0 (concatD [doc (showString "ref"), prt 0 type_, prt 0 id_])

instance Print [Lautaro.Abs.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Lautaro.Abs.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Lautaro.Abs.Stmt' a) where
  prt i = \case
    Lautaro.Abs.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    Lautaro.Abs.Skip _ -> prPrec i 0 (concatD [doc (showString "skip"), doc (showString ";")])
    Lautaro.Abs.Decl _ type_ item -> prPrec i 0 (concatD [prt 0 type_, prt 0 item, doc (showString ";")])
    Lautaro.Abs.DeclConst _ type_ item -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, prt 0 item, doc (showString ";")])
    Lautaro.Abs.VarSet _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    Lautaro.Abs.ArrSet _ id_ arrposs expr -> prPrec i 0 (concatD [prt 0 id_, prt 0 arrposs, doc (showString "="), prt 0 expr, doc (showString ";")])
    Lautaro.Abs.SReturn _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Lautaro.Abs.SVoidReturn _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Lautaro.Abs.SIf _ expr stmts -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString "then"), prt 0 stmts, doc (showString "endif")])
    Lautaro.Abs.SIfElse _ expr stmts1 stmts2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString "then"), prt 0 stmts1, doc (showString "else"), prt 0 stmts2, doc (showString "endif")])
    Lautaro.Abs.SWhile _ expr stmts -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmts, doc (showString "endwhile")])
    Lautaro.Abs.Brk _ -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    Lautaro.Abs.Cnt _ -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    Lautaro.Abs.SPrint _ expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
    Lautaro.Abs.SPut _ expr -> prPrec i 0 (concatD [doc (showString "put"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
    Lautaro.Abs.SAssert _ expr1 expr2 -> prPrec i 0 (concatD [doc (showString "assert"), doc (showString "("), prt 0 expr1, doc (showString ","), prt 0 expr2, doc (showString ")"), doc (showString ";")])
    Lautaro.Abs.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (Lautaro.Abs.Item' a) where
  prt i = \case
    Lautaro.Abs.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    Lautaro.Abs.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print (Lautaro.Abs.ArrPos' a) where
  prt i = \case
    Lautaro.Abs.ArrArg _ expr -> prPrec i 0 (concatD [doc (showString "["), prt 0 expr, doc (showString "]")])

instance Print [Lautaro.Abs.ArrPos' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Lautaro.Abs.Type' a) where
  prt i = \case
    Lautaro.Abs.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    Lautaro.Abs.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    Lautaro.Abs.Bool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    Lautaro.Abs.TArr _ type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])

instance Print (Lautaro.Abs.Expr' a) where
  prt i = \case
    Lautaro.Abs.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    Lautaro.Abs.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    Lautaro.Abs.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    Lautaro.Abs.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    Lautaro.Abs.EString _ str -> prPrec i 6 (concatD [printString str])
    Lautaro.Abs.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Lautaro.Abs.EArr _ exprs -> prPrec i 6 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    Lautaro.Abs.ArrLen _ id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "len"), doc (showString "("), prt 0 expr, doc (showString ")")])
    Lautaro.Abs.ArrDim _ id_ -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "len")])
    Lautaro.Abs.ArrApp _ id_ arrposs -> prPrec i 6 (concatD [prt 0 id_, prt 0 arrposs])
    Lautaro.Abs.StrLength _ id_ -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "length")])
    Lautaro.Abs.StrReverse _ id_ -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "reverse")])
    Lautaro.Abs.StrAppend _ id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "append"), doc (showString "("), prt 0 expr, doc (showString ")")])
    Lautaro.Abs.StrCut _ id_ expr1 expr2 -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "cut"), doc (showString "("), prt 0 expr1, doc (showString ","), prt 0 expr2, doc (showString ")")])
    Lautaro.Abs.StrReplicate _ id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "."), doc (showString "replicate"), doc (showString "("), prt 0 expr, doc (showString ")")])
    Lautaro.Abs.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Lautaro.Abs.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Lautaro.Abs.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Lautaro.Abs.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])

instance Print [Lautaro.Abs.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Lautaro.Abs.AddOp' a) where
  prt i = \case
    Lautaro.Abs.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    Lautaro.Abs.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (Lautaro.Abs.MulOp' a) where
  prt i = \case
    Lautaro.Abs.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    Lautaro.Abs.Div _ -> prPrec i 0 (concatD [doc (showString "/")])

instance Print (Lautaro.Abs.RelOp' a) where
  prt i = \case
    Lautaro.Abs.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    Lautaro.Abs.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    Lautaro.Abs.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    Lautaro.Abs.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    Lautaro.Abs.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    Lautaro.Abs.NE _ -> prPrec i 0 (concatD [doc (showString "<>")])
